gvergnaud/hotscript

- src/internals/functions/Functions.ts
- test/HOTScript.test.ts
- tsconfig.json
This add some of Functions utility types : 
- IdentityFn : to allow functional composition in the future
- Parameters: extract parameters from a function definition
- Parameter: extract one parameter from a function definition
- Return : rextract return type from a function definition
> feat(functions): add ts function utility types

- src/internals/numbers/Numbers.ts
- src/internals/numbers/impl/absolute.ts
- src/internals/numbers/impl/addition.ts
- src/internals/numbers/impl/compare.ts
- src/internals/numbers/impl/digits/addition.ts
- src/internals/numbers/impl/digits/division.ts
- src/internals/numbers/impl/digits/multiply.ts
- src/internals/numbers/impl/digits/power.ts
- src/internals/numbers/impl/digits/substraction.ts
- src/internals/numbers/impl/division.ts
- src/internals/numbers/impl/multiply.ts
- src/internals/numbers/impl/negate.ts
- src/internals/numbers/impl/numbers.ts
- src/internals/numbers/impl/power.ts
- src/internals/numbers/impl/range.ts
- src/internals/numbers/impl/substraction.ts
- src/internals/numbers/impl/utils.ts
- src/internals/strings/Strings.ts
- test/HOTScript.test.ts
Becareful, BIG, HUGE PR ahead for Numbers.
- Add
- Sub
- Mul
- Div
- Mod
- Negate
- Abs
- Power
- Compare
- Equal
- NotEqual
- LessThan
- LessThanOrEqual
- GreaterThan
- GreaterThanOrEqual
> feat(numbers): first impl

- src/internals/helpers.ts
- src/internals/strings/Strings.ts
- test/numbers.test.ts
- test/strings.test.ts
- fixing snake case and kebab case bug on first letter
- add more tests for strings
> fix(strings): fix string case and add more tests

- src/internals/numbers/Numbers.ts
just inlined docs for numbers.
> docs(numbers): add inlined docs for numbers

- README.md
- src/internals/core/Core.ts
- src/internals/functions/impl/MergeArgs.ts
- src/internals/helpers.ts
- src/internals/tuples/Tuples.ts
- test/functions.test.ts
- test/tuples.test.ts
New added features
- At
- Empty
- Zip
- ZipWith
> More tuple features

- src/internals/numbers/impl/digits/division.ts
- src/internals/numbers/impl/division.ts
- src/internals/strings/impl/repeat.ts
this simplifies repeat algorithm with a more redable one still using `O(log2(N))` algorithm.
> feat(strings): simplify repeat

- .github/workflows/node.js.yml
Should help review code and stop typos from getting pushed.
> chore: add ci

- src/internals/tuples/Tuples.ts
```ts
type A = Call<
Tuples.Map<Strings.Length>,
["a", "zvxjckvhjxhcv", "osduf", "aousdfo"]
>;
// type A = [1, 13, 5, 7]
```
> feat(tuples/map): use parallelized mapper

- src/internals/strings/impl/length.ts
- src/internals/strings/impl/repeat.ts
- src/internals/strings/impl/utils.ts
- test/strings.test.ts
This extracts PR extracts the iterator part of the algorithm that is generic from the implementation of the algorithm.
Hopefully this will allow to reuse the string iterator pattern in other future algorithms.
Ideas for future algorithms that would need the iterator : 
- CharAt<N extends integer>
- Slice v2 (would allow to slice bigger strings
- ...
> feat(strings): improve Length implementation

- src/internals/functions/Functions.ts
- test/functions.test.ts
- more inlined documentation
- make functions helpers partially appliable
> feat(functions): partial function helpers application and add inlined documentation

- src/internals/numbers/Numbers.ts
- small fix to partial apply `Mod` like other two operations
> fix(numbers): partial apply mod

- README.md
- src/internals/booleans/Booleans.ts
- test/booleans.test.ts
I tried to implement `XOr` by looking at `And` and `Or` implementations :) Added tests and updated the readme as well. Please let me know if adding it and the implementation itself make sense. Thank you!
> feat(booleans): add XOr

- README.md
- src/internals/core/Core.ts
- src/internals/match/Match.ts
- src/internals/match/impl/match.ts
- src/internals/objects/Objects.ts
- src/internals/strings/Strings.ts
- src/internals/tuples/Tuples.ts
- test/match.test.ts
- test/objects.test.ts
- test/strings.test.ts
- test/tuples.test.ts
- Strings ToRecord
- Objects Create
- Tuples ToUnion
> feat: add multiple new functions

- README.md
- src/internals/objects/Objects.ts
- src/internals/objects/impl/objects.ts
- src/internals/tuples/Tuples.ts
- test/objects.test.ts
I find this type to be very useful, should play along nicely with `Object.Get`
> implement Object.AllPaths, Object.Keys and Object.Values

- README.md
- src/internals/objects/Objects.ts
- src/internals/std/Std.ts
- test/objects.test.ts
Added Objects Required. Thanks!
> feat(objects): add Required

- README.md
- src/internals/objects/Objects.ts
- src/internals/std/Std.ts
- test/objects.test.ts
> feat(objects): add partial

- src/internals/tuples/Tuples.ts
- test/tuples.test.ts
add support for filtering readonly arrays
> feat(tuples): add support for filtering readonly arrays

- README.md
- src/internals/std/Std.ts
- src/internals/unions/Unions.ts
- test/unions.test.ts
> feat(unions): add NonNullable

- README.md
- src/internals/booleans/Booleans.ts
- src/internals/functions/Functions.ts
- src/internals/match/Match.ts
- src/internals/match/impl/match.ts
- src/internals/numbers/Numbers.ts
- src/internals/strings/Strings.ts
- src/internals/tuples/Tuples.ts
- src/internals/unions/Unions.ts
- test/match.test.ts
- test/strings.test.ts
- test/tuples.test.ts
- test/unions.test.ts
Added `Reverse` to `Tuples`. Removed unused imports from various files.
> feat: add reverse

- package-lock.json
- package.json
Fixes issue https://github.com/gvergnaud/hotscript/issues/96
> Fix for ts bundler
